version: '3'

services:
  db:
    image: 'mariadb'
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_USER=$DATABASE_USER
      - MYSQL_PASSWORD=$DATABASE_PASSWORD
      - MYSQL_DATABASE=$DATABASE_NAME
      - MARIADB_RANDOM_ROOT_PASSWORD=1
    networks:
      - elgg-network

  elgg:
    image: 'calteknet/elgg:latest'
    user: ctn
    ports:
      - 9000
    depends_on:
      - db
    networks:
      - elgg-network
    volumes:
      - static-data:/opt/static
      - elgg-data:/opt/data
  
  nginx:
    image: 'localhost/calteknet/nginx:latest'
    user: ctn
    ports:
      - $NGINX_PORT:8000
    links:
      - elgg:php-fpm
    depends_on:
      - elgg
    networks:
      - elgg-network
    volumes:
      - static-data:/opt/static
    # cap_add:
    #   - NET_ADMIN
    #   - NET_RAW

volumes:
  mariadb-data:
  elgg-data:
  static-data:

networks:
  elgg-network:
