version: '3'
services:
  db:
    image: 'mariadb'
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MARIADB_USER=$DATABASE_USER
      - MARIADB_PASSWORD=$DATABASE_PASSWORD
      - MARIADB_DATABASE=$DATABASE_NAME
      - MARIADB_RANDOM_ROOT_PASSWORD=1
    networks:
      - elgg-network
  elgg:
    image: 'calteknet/elgg:latest'
    user: ctn
    depends_on:
      - db
    networks:
      - elgg-network
      - traefik-public
    volumes:
      - static-data:/opt/static
      - elgg-data:/opt/data
        
  nginx:
    image: 'nginx:stable'
    # Remove the user: ctn line since nginx needs root permissions
    links:
      - elgg:php-fpm
    depends_on:
      - elgg
    networks:
      # - elgg-network
      - traefik-public
    volumes:
      - static-data:/opt/static
      - /home/kmw/config/elgg/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.elgg.rule=Host(`idea.caltek.net`)"
        - "traefik.http.routers.elgg.entrypoints=websecure"
        - "traefik.http.routers.elgg.tls=true"
        - "traefik.http.routers.elgg.tls.certresolver=letsencrypt"
        - "traefik.http.services.elgg.loadbalancer.server.port=80"
volumes:
  mariadb-data:
  elgg-data:
  static-data:
networks:
  elgg-network:
  traefik-public:
    external: true