version: '3'

services:
  mariadb:
    image: 'mariadb:latest'
    container_name: mariadb
    env_file: db-vars.env
    volumes:
      - 'mariadb-data:/var/lib/mysql'
    networks:
      - elgg-network

  elgg:
    image: 'localhost/calteknet/elgg:latest'
    container_name: elgg 
    # env_file: elgg-vars.env
    ports:
      - 9000
    # volumes:
    #   - 'elgg-data:/bitnami/moodle'
    depends_on:
      - mariadb
    networks:
      - elgg-network
  
  nginx:
    image: 'localhost/calteknet/nginx:latest'
    container_name: nginx
    ports:
      - $NGINX_PORT:8000
    links:
      - elgg:php-fpm
    depends_on:
      - elgg
    networks:
      - elgg-network

volumes:
  mariadb-data:
    driver: local
  elgg-data:
    driver: local

networks:
  elgg-network:
