version: '3'
volumes:
  mariadb-dataa:
    driver: local
  moodle-dataa:
    driver: local
networks:
    moodle-network:
services:
  mariadb2:
    image: 'mariadb:latest'
    container_name: mariadb2
    env_file: db-vars.env
    volumes:
      - 'mariadb-dataa:/var/lib/mysql'
    networks:
      - moodle-network
  moodle2:
    image: 'bitnami/moodle:latest'
    container_name: moodle2
    env_file: moodle-vars.env
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'moodle-dataa:/bitnami/moodle'
    depends_on:
      - mariadb2
    networks:
      - moodle-network



